services:
  web:
    build:
      context: .
    command: bin/dev
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      NODE_ENV: development
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
      - ./db:/rails/db 
    stdin_open: true
    tty: true

volumes:
  bundle:
  node_modules:
